name: ci

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # 1️⃣ Build and run tests
            - name: Build & Test
              run: |
                  docker build --target test -t ci-test .
                  docker run --rm ci-test

            # 2️⃣ Build production image
            - name: Build Production Image
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  target: prod
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

            # 3️⃣ Trigger Render Deploy
            - name: Deploy to Render
              run: |
                  curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
                  -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                  -H "Content-Type: application/json" \
                  -d '{"clearCache":true}'
